#Faça um programa que leia algo pelo teclado e mostre que tipo primnitivo e todas as informações possíveis sobre ele.
something = input('Digite algo: ')
print('O tipo primitivo desse valor é: '.format(type(something)))
print('Só tem espaços? {}'.format(something.isspace()))
print('É um número? {}'.format(something.isnumeric()))
print('É alfabético? {}'.format(something.isalpha()))
print('É alfanumérico? {}'.format(something.isalnum()))
print('Está em maiúsculo? {}'.format(something.isupper()))
print('Está em minúsculo? {}'.format(something.islower()))
print('Está capitalizada? {}'.format(something.istitle()))